### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by thirdreplicator** [oleksiyk/no-riak#1]
Hi,
  I would like to develop a thin convenience wrapper around your more powerful and complete library, and I would like to make it MIT licensed so that anybody could do whatever they like with the software.  Is your license compatible with the MIT license?  I'd be happy to add your name to the license if you would like it to appear there.
  Kind regards,
  David :)

**Comment by thirdreplicator** [comment]
Here is the project I'm talking about:

https://github.com/thirdreplicator/raku

**Comment by thirdreplicator** [comment]
Oh, it seems that you have an MIT license too.

**Comment by oleksiyk** [comment]
You’re welcome
