### ISSUE TITLE
List of Bucket Types

### ISSUE THREAD

**Issue by thirdreplicator** [oleksiyk/no-riak#3]
Hi,
  How can you get a list of all bucket-types?
Thank you.

**Comment by oleksiyk** [comment]
https://github.com/oleksiyk/no-riak/blob/master/lib/client.js#L297

**Comment by thirdreplicator** [comment]
Hi,
  I tried that and it gives a list of KV buckets, and not CRDT buckets created at the command-line, if any.  Also, it doesn't include bucket types [http://docs.basho.com/riak/kv/2.2.0/developing/usage/bucket-types/](http://docs.basho.com/riak/kv/2.2.0/developing/usage/bucket-types/)

**Comment by oleksiyk** [comment]
This call doesn't list bucket types, it lists buckets. If you need to list buckets of specific type, include that type in params:

```
client.listBuckets({ type: 'mytype' })
```

**Comment by oleksiyk** [comment]
There is no API call to list bucket types. You can only do that from console:

`riak-admin bucket-type list`

**Comment by thirdreplicator** [comment]
thanks a lot!
